image: jdrouet/docker-with-buildx:stable

services:
  - docker:dind

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build
  - build-stage

build:
  stage: build
  script:
    - docker buildx create --use
    - docker buildx create --name multiarch-builder --driver docker-container --use tls-environment
    - docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main

build-stage:
  stage: build-stage
  script:
    - docker pull $CI_REGISTRY_IMAGE:stage || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:stage --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:stage .
    # - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:stage
  only:
    - features

