version: '3.7'

services:
  # postgres:
  #   image: postgres
  #   volumes:
  #     #- postgres_data:/var/lib/postgresql/data
  #     - ./data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_DB: keycloak
  #     POSTGRES_USER: keycloak
  #     POSTGRES_PASSWORD: password
  # keycloak:
  #   image: quay.io/keycloak/keycloak:latest
  #   environment:
  #     DB_VENDOR: POSTGRES
  #     DB_ADDR: postgres
  #     DB_DATABASE: keycloak
  #     DB_USER: keycloak
  #     DB_SCHEMA: public
  #     DB_PASSWORD: password
  #     KEYCLOAK_USER: admin
  #     KEYCLOAK_PASSWORD: Pa55w0rd
  #         # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
  #         #JDBC_PARAMS: "ssl=true"
  #   depends_on:
  #     - postgres
  #   ports:
  #     - 8080:8080

  app:
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    env_file:
    - .env
    environment:
      - NODE_ENV=production     
      - PORT=8181
      - DOCKER=true
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_DB=${DB_DATABASE}
    # depends_on:
    #   - keycloak
    ports:
      - 8181:8181

volumes:
  postgres_data:
      driver: local  